### ISSUE TITLE
Error when using Database.nonBlocking()

### ISSUE THREAD

**Issue by japonicius** [davidmoten/rxjava2-jdbc#16]
Hello David,

I'm trying to use the `Database.nonBlocking().connectionProvider(dataSource).build()` but I keep getting this Exception `org.davidmoten.rx.pool.PoolClosedException: null`.

If I switch to `Database.fromBlocking(dataSource)` it works fine.

This is my db call
```
import javax.sql.DataSource;
import org.davidmoten.rx.jdbc.Database;
import org.davidmoten.rx.jdbc.ResultSetMapper;

try (Database db = Database.fromBlocking(dataSource)) {
            return db
                    .select(query)
                    .parameter("param1", param1)
                    .parameter("param2", param2)
                    .parameter("param3", param3)
                    .parameter("param4", param4)
                    .get(new MyObjectMapper());
        }
```

As always thank you very much for your time!

**Comment by japonicius** [comment]
When I don't use try with resources, I get connection leak issues
```
java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
        at org.davidmoten.rx.jdbc.Util.getConnection(Util.java:1069)
        at org.davidmoten.rx.jdbc.Util$5.get(Util.java:1056)
        at org.davidmoten.rx.jdbc.pool.NonBlockingConnectionPool$Builder.lambda$build$1(NonBlockingConnectionPool.java:229)
        at org.davidmoten.rx.jdbc.pool.NonBlockingConnectionPool$Builder$$Lambda$18/663326227.call(Unknown Source)
        at org.davidmoten.rx.pool.MemberSingle$Initializer.run(MemberSingle.java:336)
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by davidmoten** [comment]
Ah yep I see. So, close the `db` then but only once the stream has been processed (subscription has happened and terminal event received).

**Comment by japonicius** [comment]
what is the trade-off by using `try (Database db = Database.fromBlocking(dataSource)) {`?
Isn't the creating of database resource intensive?

**Comment by davidmoten** [comment]
No, the creation is not intensive. No connections are opened when you call `Database.fromBlocking(dataSource)`. Connections are requested when needed from the `dataSource` only when you subscribe to a flowable created using the `db`. Connection pooling is completely handled by the `dataSource`.

**Comment by davidmoten** [comment]
>When I don't use try with resources, I get connection leak issues

I'll just think that through. I might have an issue to chase there.

**Comment by davidmoten** [comment]
Thanks for raising this. I confirm there is a bug in `Database.fromBlocking` where it does not close connections. We didn't have test coverage of `fromBlocking`, now we do!

I've released the fix 0.1-RC27 to Maven Central, please give it a try.

**Comment by japonicius** [comment]
Awesome!

**Comment by japonicius** [comment]
What about using A singleton `Database.nonBlocking().connectionProvider(dataSource).build()`, << this is when I was getting connection leaks as well

**Comment by japonicius** [comment]
@davidmoten maven central only has up to RC23
https://mvnrepository.com/artifact/com.github.davidmoten/rxjava2-jdbc

**Comment by davidmoten** [comment]
>What about using a singleton Database.nonBlocking().connectionProvider(dataSource).build(), << this is when I was getting connection leaks as well

That is to be expected because the non-blocking `Database` has its own connection pool. In this case I would avoid using hikari underneath or configure hikari not to complain about connections that are open for a long time.

**Comment by davidmoten** [comment]
>maven central only has up to RC23

Thanks, that's annoying. Something has changed in the sonatype deployment space and I had troubles yesterday. What you can do is build it yourself locally from the tag:

```bash
cd rxjava2-jdbc
git pull
git fetch --tags
git checkout 0.1-RC27
mvn clean install
```
I'll sort out deployment to Maven Central in the next couple of days hopefully.

**Comment by davidmoten** [comment]
Deployment sorted out. You can use 0.1-RC29 from Maven Central.

**Comment by japonicius** [comment]
awesome!
