### ISSUE TITLE
concurrency test failure in 0.1-RC2

### ISSUE THREAD

**Issue by davidmoten** [davidmoten/rxjava2-jdbc#2]
Concurrency testing threw ArrayIndexOutOfBoundsException as below. Problem has been identified and fix coming soon.
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 35
	at org.davidmoten.rx.pool.MemberSingle.emit(MemberSingle.java:130)
	at org.davidmoten.rx.pool.MemberSingle.drain(MemberSingle.java:106)
	at org.davidmoten.rx.pool.MemberSingle.subscribeActual(MemberSingle.java:182)
	at io.reactivex.Single.subscribe(Single.java:2700)
	... 13 more
```

**Comment by davidmoten** [comment]
Fix released in 0.1-RC3 on Maven Central
