### ISSUE TITLE
Observable database is closed but flowable is ok

### ISSUE THREAD

**Issue by snodnipper** [davidmoten/rxjava2-jdbc#6]
Using: `com.github.davidmoten:rxjava2-jdbc:0.1-RC8`
with `org.xerial:sqlite-jdbc:3.20.0`

Given this code:

```java
  private final Database dataSource;
  ...
  Connection connection = DriverManager.getConnection("jdbc:sqlite:" + fileLocation)
  datasource = Database.from(Single.just(connection)...
  ...
  private Observable<VectorTileConfig> queryConfig() {
      return queryConfigFlowable().toObservable();
  }

  private Flowable<VectorTileConfig> queryConfigFlowable() {
    final URL url = Resources.getResource("metadata_raw.sql");
    String query;
    try {
      query = Resources.toString(url, Charsets.UTF_8);
    } catch (final IOException ex) {
      return Flowable.error(ex);
    }
    return dataSource.select(query)
        .get(rs -> new VectorTileConfig(rs.getInt("min_zoom"), rs.getInt("max_zoom"),
            rs.getInt("max_zoom_minx"), rs.getInt("max_zoom_miny"), rs.getInt("max_zoom_maxx"),
            rs.getInt("max_zoom_maxy")));
  }
```

I note that reusing the database/`datasource` has different behaviour.  As an observable, the _second query_ results in:
<details>
<summary>Caused by: java.sql.SQLException: database connection closed</summary>

	at io.reactivex.observers.BaseTestConsumer.fail(BaseTestConsumer.java:163)
	at io.reactivex.observers.BaseTestConsumer.assertValue(BaseTestConsumer.java:328)
	at uk.os.vt.mbtiles.StorageImplCannedDataTest.testMultipleZoomLevelMaxZoom(StorageImplCannedDataTest.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Caused by: java.sql.SQLException: database connection closed
	at org.sqlite.core.CoreConnection.checkOpen(CoreConnection.java:336)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:45)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
	at org.davidmoten.rx.jdbc.Util.prepare(Util.java:293)
	at org.davidmoten.rx.jdbc.Select.lambda$create$1(Select.java:39)
	at io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:49)
	at io.reactivex.Flowable.subscribe(Flowable.java:12994)
	at io.reactivex.Flowable.subscribe(Flowable.java:12940)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:133)
	at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:63)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
	at io.reactivex.Flowable.subscribe(Flowable.java:12994)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:12994)
	at io.reactivex.Flowable.subscribe(Flowable.java:12940)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10910)
	at uk.os.vt.mbtiles.StorageImplCannedDataTest.testMultipleZoomLevelMaxZoom(StorageImplCannedDataTest.java:176)
	... 22 more
</details>
<br />
When using the Flowable I can execute multiple queries without issue.

Let me know if you'd like a PR with failing test...or if I have missed something obvious.  Thanks.

**Comment by davidmoten** [comment]
This is a documentation issue. You are using a low-level method and you need to know how it works (and I need to document that method in the javadoc). When the first query is run the `Connection.close()` method is called. When you use the Database or Pool builders the actual Connections are wrapped with a Connection that overrides the `close` method so that the Connection does not get closed but rather just gets returned to the pool.

You should do this (from the README.md):

```java
Database db = Database.from("jdbc:sqlite:" + fileLocation, 1);
```

**Comment by snodnipper** [comment]
Excellent, thanks David - it works a treat now.  We really appreciate efforts in making rxjava2-jdbc 👍
